# Generated by Django 5.2.17 on 2026-09-03 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('niveau', models.CharField(max_length=50)),
                ('effectif', models.PositiveIntegerField(default=0)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=20)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauEDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10)),
                ('heure_debut', models.CharField(max_length=5)),
                ('heure_fin', models.CharField(max_length=5)),
                ('salle', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['classe', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('couleur', models.CharField(default='#2563a8', max_length=7)),
            ],
            options={
                'ordering': ['classe', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('type', models.CharField(choices=[('devoir', 'Devoir'), ('examen', 'Composition'), ('interrogation', 'Interrogation')], max_length=20)),
                ('date', models.DateField()),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Urgent')], default='info', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('inscription', 'Inscription'), ('mensualite', 'Mensualité'), ('transport', 'Transport'), ('cantine', 'Cantine')], max_length=20)),
                ('status', models.CharField(choices=[('payé', 'Payé'), ('impayé', 'Impayé'), ('partiel', 'Partiel')], default='impayé', max_length=10)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('mois', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('présent', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excusé', 'Excusé')], max_length=10)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
