# Generated by Django 5.2.17 on 2026-09-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, help_text="Le titulaire de la classe : voit le bulletin complet, même s'il n'enseigne pas toutes les matières.", limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_titulaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creneauedt',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi_du_temps', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creneauedt',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='academics.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.eleve'),
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='academics.eleve'),
        ),
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='academics.eleve'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='creneauedt',
            unique_together={('jour', 'heure_debut', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'date')},
        ),
    ]
