# Generated by Django 5.2.17 on 2026-09-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AlterUniqueTogether(
            name='creneauedt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creneauedt',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='creneauedt',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='eleve',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='presence',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='CreneauEDT',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
