# Generated by Django 5.2.17 on 2026-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='couleur_bulletin',
            field=models.CharField(blank=True, default='', help_text="Couleur d'accent du bulletin de cette classe (ex. #2563a8). Vide = couleur par défaut de l'établissement.", max_length=7),
        ),
        migrations.AddField(
            model_name='classe',
            name='couleur_fond_bulletin',
            field=models.CharField(blank=True, default='', help_text="Couleur de fond du bulletin de cette classe (ex. #ffffff). Vide = couleur par défaut de l'établissement.", max_length=7),
        ),
    ]
